version: 2.1
jobs:
  test:
    docker:
      - image: hysds/pge-base:latest
    steps:
      - checkout
      - run:
          name: Test
          command: |
            source $HOME/verdi/bin/activate
            pip install j2cli
            j2 --undefined $HOME/verdi/ops/hysds/configs/celery/celeryconfig.py.tmpl -o $HOME/verdi/ops/hysds/celeryconfig.py
            python setup.py test
          environment:
            MOZART_ES_PVT_IP: 127.0.0.1
            GRQ_ES_PVT_IP: 127.0.0.1

workflows:
  version: 2
  test:
    jobs:
      - test
  weekly:
    triggers:
      - schedule:
          cron: "0 7 * * 0"
          filters:
            branches:
              only:
                - develop
    jobs:
      - test:
          filters:
            branches:
              only: develop
