#!/usr/bin/env python
# -----------------------------------------------------------------------------
# Name:        basicPageTemplate.py
# Purpose:     Custom web page layout templates.
#
# Author:      Gerald Manipon
#
# Created:     Thu Jul 27 11:10:00 2006
# Copyright:   (c) 2006, California Institute of Technology.
#              U.S. Government Sponsorship acknowledged.
# -----------------------------------------------------------------------------
from string import Template
import os
import re
from sciflo.utils import getHtmlBaseHref, getCgiBaseHref, getRelativeUrl, sanitizeHtml

CGI_URL_BASE = getCgiBaseHref()
HTML_URL_BASE = getHtmlBaseHref()
REL_URL = getRelativeUrl(CGI_URL_BASE, HTML_URL_BASE)
DOJO_URL = os.path.join(REL_URL, 'dojo/dojo.js')
EXT_URL = os.path.join(REL_URL, 'ext')
EXTBASEX_URL = os.path.join(REL_URL, 'ext-basex')

customHead = '''
<base href="%s">
<script language="Javascript">
var newWindow;
function popup(url, name, width, height) {
  if (newWindow) {
    if (newWindow.closed == false) {
      newWindow.focus();
    }
  }
  wstyle="toolbar=0,status=0,menubar=0,scrollbars=1,resizable=1,width="+width+",height="+height;
  newWindow=window.open(url, name, wstyle);
}
</script>
<script language="JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++)
x.src=x.oSrc;
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length;
i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length)
{
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++)
x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++)
x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array;
for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc)
x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>

<link rel="stylesheet" type="text/css"
      href="genesis.css">

<meta name="description" content="GENESIS (Global Environmental &amp; Earth Science Information System)
is a suite of data services that bring together the Earth science products generated by spaceborne
Global Positioning System (GPS) receivers flying on several international missions.  GENESIS
provides a database for GPS occultation observations from the CHAMP and SAC-C spacecraft,
which carry NASA-supplied GPS receivers designed for atmospheric and ionospheric sounding.
The flight database is augmented with GPS ground data and a variety of higher level derived
products. We hope soon that occultation data from the GRACE mission can be added to this unique
archive.  In the future, under NASA's REASoN (Research, Education, and Applications Solution
Network) Program, GENESIS will expand its role to support more general Earth science
investigations involving data from multiple flight instruments, providing specialized tools
for mining, visualization, fusion, and analysis of large science data sets.  A demonstration
version of the new GENESIS will be available in 2005." />
''' % getHtmlBaseHref()

customBodyStart = '''
'''

customBodyEnd = '''
'''

pageTemplateHead = Template('''
<html>
 <head>
  <title>${title}</title>
  <!--EXT_BEGIN-->
  <link rel="stylesheet" type="text/css" href="%s/resources/css/ext-all.css" />
  <script type="text/javascript" src="%s/adapter/ext/ext-base.js"> </script>
  <script type="text/javascript" src="%s/ext-all-debug.js"> </script>
  <script type="text/javascript" src="%s/ext-basex.js"> </script>
  <script type="text/javascript">
      Ext.QuickTips.init();
  </script>
  <!--EXT_END-->
  <!--DOJO_BEGIN-->
  <script type="text/javascript">
    djConfig = { isDebug: false };
  </script>
  <script type="text/javascript" src="%s"></script>
  <script type="text/javascript">
    dojo.require("dojo.event.*");
    dojo.require("dojo.io.*");
    dojo.require("dojo.widget.ComboBox");
  </script>
  <script type="text/javascript">
    function waitForLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadXmlToWindow(str, id);
      }else {
        dojo.lang.setTimeout(waitForLoad, 300, id);
      }
    }

    function getXmlStr(id) {
      var xmlDoc = document.getElementById(id);
      return getXmlStringFromCDATAString(xmlDoc.childNodes[0].nodeValue);
    }

    function loadXmlToWindow(str, id) {
      var newwin = window.open('data:text/xml,' + str, id);
    }

    function loadResultToWindow(str) {
      var newwin = window.open();
      var newdoc = newwin.document;
      newdoc.write(str);
      newdoc.close();
    }

    function waitForResultLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadResultToWindow(str);
      }else {
        dojo.lang.setTimeout(waitForResultLoad, 300, id);
      }
    }
  </script>
  <!--DOJO_END-->
  %s
  ${additionalHead}
 </head>
 <body ${bodyOnload}>
 <a href="%s#main"><img src="portal_images/spacer.gif" alt="Follow this link to skip to the main content"
width="1" height="1" hspace="0" vspace="0" border="0" align="left"></a>
 %s
<noscript>
<font color="red">
JavaScript is turned off in your web browser. Turn it on to make this site functional, then refresh the page.
</font><br><br>
</noscript>
''' % (EXT_URL, EXT_URL, EXT_URL, EXTBASEX_URL, DOJO_URL, customHead, sanitizeHtml(os.environ['REQUEST_URI']), customBodyStart))

pageTemplateHeadStart = Template('''
<html>
 <head>
  <title>${title}</title>
  <!--EXT_BEGIN-->
  <link rel="stylesheet" type="text/css" href="%s/resources/css/ext-all.css" />
  <script type="text/javascript" src="%s/adapter/ext/ext-base.js"> </script>
  <script type="text/javascript" src="%s/ext-all-debug.js"> </script>
  <script type="text/javascript" src="%s/ext-basex.js"> </script>
  <script type="text/javascript">
      Ext.QuickTips.init();
  </script>
  <!--EXT_END-->
  <!--DOJO_BEGIN-->
  <script type="text/javascript">
    djConfig = { isDebug: false };
  </script>
  <script type="text/javascript" src="%s"></script>
  <script type="text/javascript">
    dojo.require("dojo.event.*");
    dojo.require("dojo.io.*");
    dojo.require("dojo.widget.ComboBox");
  </script>
  <script type="text/javascript">
    function waitForLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadXmlToWindow(str, id);
      }else {
        dojo.lang.setTimeout(waitForLoad, 300, id);
      }
    }

    function getXmlStr(id) {
      var xmlDoc = document.getElementById(id);
      return getXmlStringFromCDATAString(xmlDoc.childNodes[0].nodeValue);
    }

    function loadXmlToWindow(str, id) {
      var newwin = window.open('data:text/xml,' + str, id);
    }

    function loadResultToWindow(str) {
      var newwin = window.open();
      var newdoc = newwin.document;
      newdoc.write(str);
      newdoc.close();
    }

    function waitForResultLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadResultToWindow(str);
      }else {
        dojo.lang.setTimeout(waitForResultLoad, 300, id);
      }
    }
  </script>
  <!--DOJO_END-->
  %s
  ${additionalHead}
''' % (EXT_URL, EXT_URL, EXT_URL, EXTBASEX_URL, DOJO_URL, customHead))

pageTemplateHeadEnd = Template('''
  ${additionalHead}
</head>
 <body ${bodyOnload}>
 <a href="%s#main"><img src="portal_images/spacer.gif" alt="Follow this link to skip to the main content"
width="1" height="1" hspace="0" vspace="0" border="0" align="left"></a>
 %s
<noscript>
<font color="red">
JavaScript is turned off in your web browser. Turn it on to make this site functional, then refresh the page.
</font><br><br>
</noscript>
''' % (sanitizeHtml(os.environ['REQUEST_URI']), customBodyStart))

pageTemplateFoot = Template('%s</body></html>' % customBodyEnd)
