#!/usr/bin/env python
# -----------------------------------------------------------------------------
# Name:        pageTemplate.py
# Purpose:     Custom web page layout templates.
#
# Author:      Gerald Manipon
#
# Created:     Thu Jul 27 11:10:00 2006
# Copyright:   (c) 2006, California Institute of Technology.
#              U.S. Government Sponsorship acknowledged.
# -----------------------------------------------------------------------------
from string import Template
import os
import re
from sciflo.utils import getHtmlBaseHref, getCgiBaseHref, getRelativeUrl, sanitizeHtml

CGI_URL_BASE = getCgiBaseHref()
HTML_URL_BASE = getHtmlBaseHref()
REL_URL = getRelativeUrl(CGI_URL_BASE, HTML_URL_BASE)
DOJO_URL = os.path.join(REL_URL, 'dojo/dojo.js')
EXT_URL = os.path.join(REL_URL, 'ext')
EXTBASEX_URL = os.path.join(REL_URL, 'ext-basex')

customHead = '''
<script language="Javascript">
var newWindow;
function popup(url, name, width, height) {
  if (newWindow) {
    if (newWindow.closed == false) {
      newWindow.focus();
    }
  }
  wstyle="toolbar=0,status=0,menubar=0,scrollbars=1,resizable=1,width="+width+",height="+height;
  newWindow=window.open(url, name, wstyle);
}
</script>
<script language="JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++)
x.src=x.oSrc;
}
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length;
i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
function MM_findObj(n, d) { //v4.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length)
{
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++)
x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++)
x=MM_findObj(n,d.layers[i].document);
  if(!x && document.getElementById) x=document.getElementById(n); return x;
}
function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array;
for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc)
x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>

<link rel="stylesheet" type="text/css"
      href="common.css">

<meta name="description" content="GENESIS (Global Environmental &amp; Earth Science Information System)
is a suite of data services that bring together the Earth science products generated by spaceborne
Global Positioning System (GPS) receivers flying on several international missions.  GENESIS
provides a database for GPS occultation observations from the CHAMP and SAC-C spacecraft,
which carry NASA-supplied GPS receivers designed for atmospheric and ionospheric sounding.
The flight database is augmented with GPS ground data and a variety of higher level derived
products. We hope soon that occultation data from the GRACE mission can be added to this unique
archive.  In the future, under NASA's REASoN (Research, Education, and Applications Solution
Network) Program, GENESIS will expand its role to support more general Earth science
investigations involving data from multiple flight instruments, providing specialized tools
for mining, visualization, fusion, and analysis of large science data sets.  A demonstration
version of the new GENESIS will be available in 2005." />
'''
customHead = re.sub(r'common.css', os.path.join(
    REL_URL, 'common.css'), customHead)

customBodyStart = '''
<table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td bgcolor="#ffffff" align="center"></td></tr>
<tr><td bgcolor="#000000">
<table border="0" cellspacing="0" cellpadding="0" align="center" valign="top" bgcolor="#FFFFFF" width="750">

<tr bgcolor="#000000">
<td bgcolor="#000000" width="10"><img alt="spacer"
    width="10" height="1"
    src="portal_images/spacer.gif"></td>
<td bgcolor="#000000" width="730"><img alt="spacer"
    width="730" height="10"
    src="portal_images/spacer.gif"></td>
<td bgcolor="#000000" width="10"><img alt="spacer"
    width="10" height="1"
    src="portal_images/spacer.gif"></td>
</tr>
<tr>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
<td width="730"><img alt="spacer" width="730" height="10"
                     src="portal_images/spacer.gif"></td>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
</tr>
<tr>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
<td width="730">
	<table cellpadding="0" cellspacing="0" border="0" width="730">

		<tr>

			<td>
				<table cellpadding="0" cellspacing="0" border="0" width="730">
					<tr>
						<td width="379" bgcolor="#cccccc"><img
    alt="NASA Logo - Jet Propulsion Laboratory" border="0"
    width="379" height="65" usemap="#Map"
    src="portal_images/nasa_logo.gif"></td>
						<td width="171" bgcolor="#cccccc">&nbsp;&nbsp;&nbsp;<a class="navLnkBlack" href="http://www.nasa.gov">+ View the NASA Portal</a></td>
						<td width="180" bgcolor="#006699" align="center" valign="middle"><font size="2" face="arial" color="#ffffff">Search JPL</font>

						<form method="get" action="http://search.jpl.nasa.gov:8080/cgi-bin/htsearch">
						<input alt="words" type="textbox" name="words" size="10" maxlength="200" value=""><input
    title="search" type="image" height="14" width="16"
    name="search" border="0"
    src="portal_images/arrow.gif">

                		</form>
						</td>
					</tr>
				</table>
			</td>
		</tr>

<tr><td><img alt="spacer" width="730" height="3"
             src="portal_images/spacer.gif"></td></tr>
        <tr>
          <td>	<table cellpadding="0" cellspacing="0" border="0"><tr>

			<td><a href="http://www.jpl.nasa.gov/index.cfm" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('home','','portal_images/topnav_01.gif',1)"><img
    name="home" border="0" alt="JPL Home"
    src="portal_images/topnavoff_01.gif"></a></td>
			<td><a href="http://www.jpl.nasa.gov/earth/" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('earth','','portal_images/topnav_02.gif',1)"><img
    name="earth" border="0" alt="Earth"
    src="portal_images/topnavoff_02.gif"></a></td>
			<td><a href="http://www.jpl.nasa.gov/solar_system/" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('solar_system','','portal_images/topnav_03.gif',1)"><img
    name="solar_system" alt="Solar System" border="0"
    src="portal_images/topnavoff_03.gif"></a></td>
			<td><a href="http://www.jpl.nasa.gov/stars_galaxies/" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('stars','','portal_images/topnav_04.gif',1)"><img
    name="stars" border="0" alt="Stars &amp; Galaxies"
    src="portal_images/topnavoff_04.gif"></a></td>
			<td><a href="http://www.jpl.nasa.gov/technology/" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('technology','','portal_images/topnav_05.gif',1)"><img
    name="technology" border="0" alt="Technology"
    src="portal_images/topnavoff_05.gif"></a></td>
		</tr></table>

	  </td>
        </tr>
		<tr>


        <td width="730"><img width="730" vspace="3"
                             alt="GENESIS Global Environmental and Earth Science Information Systems" border="0"
                             src="portal_images/genesis_banner.jpg"></td>
		</tr>
	</table>
</td>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
</tr>


<tr>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
<td width="730"><img alt="spacer" width="730" height="10"
                     src="portal_images/spacer.gif"></td>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
</tr>

<tr>

<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
<td>
<!--HEADERTEMPLATEEND-->
<table cellspacing="0" cellpadding="0" border="0"
       width="740">
               <tr><td>
                 <img alt="spacer" width="100%" height="1"
                      src="portal_images/cccccc_1pixel.gif">
               </td></tr>
               <tr><td><br></td></tr>
               <tr><td>
'''
customBodyStart = re.sub(r'portal_images', os.path.join(
    REL_URL, 'portal_images'), customBodyStart)

customBodyEnd = '''
</td></tr>
</table>
<!--HEADERTEMPLATEEND-->

</td>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
</tr>
<tr>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
<td width="730"><img alt="spacer" width="730" height="10"
                     src="portal_images/spacer.gif"></td>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
</tr>


<tr>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
<td bgcolor="#cccccc"><table cellpadding="4" cellspacing="0" width="730" border="0"><tr>
          <td valign="top" width="160"><a target="_blank" href="http://www.firstgov.gov/"><img
    height="39" alt="FIRST GOV" width="136" border="0"
    src="portal_images/footer_image1.gif"></a></td>
          <td width="198">&nbsp;</td>

          <td width="198"><a class="featurelnk" href="http://www.jpl.nasa.gov/copyrights.cfm">+ Privacy / Copyright</a></td>

          <td width="61"><a target="_blank" href="http://www.nasa.gov/home/index.html"><img
    height="40" alt="NASA Home Page" width="61" border="0"
    src="portal_images/footer_image2.gif"></a></td>

        <td width="280"><!--<font face="Arial, Helvetica, sans-serif" size="2">
          Webmaster: [Your name here]</font>--></td>
        </tr></table>
	</td>

<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
</tr>
<tr>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
<td width="730"><img alt="spacer" width="730" height="10"
                     src="portal_images/spacer.gif"></td>
<td width="10"><img alt="spacer" width="10" height="1"
                    src="portal_images/spacer.gif"></td>
</tr>
<tr bgcolor="#000000">

<td bgcolor="#000000" width="10"><img alt="spacer"
    width="10" height="1"
    src="portal_images/spacer.gif"></td>
<td bgcolor="#000000" width="730"><img alt="spacer"
    width="730" height="10"
    src="portal_images/spacer.gif"></td>
<td bgcolor="#000000" width="10"><img alt="spacer"
    width="10" height="1"
    src="portal_images/spacer.gif"></td>
</tr>
</table>



<map name="Map">
  <area shape="rect" alt="JPL" coords="91,6,278,30" href="http://www.jpl.nasa.gov">
  <area shape="circle" alt="NASA" coords="56,27,24" href="http://www.nasa.gov">
  <area shape="rect" alt="Caltech" coords="91,31,272,49" href="http://www.caltech.edu/">
</map>


</td></tr></table>
'''
customBodyEnd = re.sub(r'portal_images', os.path.join(
    REL_URL, 'portal_images'), customBodyEnd)

pageTemplateHead = Template(re.sub(r'portal_images', os.path.join(REL_URL, 'portal_images'), '''
<html>
 <head>
  <title>${title}</title>
  <!--EXT_BEGIN-->
  <link rel="stylesheet" type="text/css" href="%s/resources/css/ext-all.css" />
  <script type="text/javascript" src="%s/adapter/ext/ext-base.js"> </script>
  <script type="text/javascript" src="%s/ext-all-debug.js"> </script>
  <script type="text/javascript" src="%s/ext-basex.js"> </script>
  <script type="text/javascript">
      Ext.QuickTips.init();
  </script>
  <!--EXT_END-->
  <!--DOJO_BEGIN-->
  <script type="text/javascript">
    djConfig = { isDebug: false };
  </script>
  <script type="text/javascript" src="%s"></script>
  <script type="text/javascript">
    dojo.require("dojo.event.*");
    dojo.require("dojo.io.*");
    dojo.require("dojo.widget.ComboBox");
  </script>
  <script type="text/javascript">
    function waitForLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadXmlToWindow(str, id);
      }else {
        dojo.lang.setTimeout(waitForLoad, 300, id);
      }
    }

    function getXmlStr(id) {
      var xmlDoc = document.getElementById(id);
      return getXmlStringFromCDATAString(xmlDoc.childNodes[0].nodeValue);
    }

    function loadXmlToWindow(str, id) {
      var newwin = window.open('data:text/xml,' + str, id);
    }

    function loadResultToWindow(str) {
      var newwin = window.open();
      var newdoc = newwin.document;
      newdoc.write(str);
      newdoc.close();
    }

    function waitForResultLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadResultToWindow(str);
      }else {
        dojo.lang.setTimeout(waitForResultLoad, 300, id);
      }
    }
  </script>
  <!--DOJO_END-->
  %s
  ${additionalHead}
 </head>
 <body ${bodyOnload}>
 <a href="%s#main"><img src="portal_images/spacer.gif" alt="Follow this link to skip to the main content"
width="1" height="1" hspace="0" vspace="0" border="0" align="left"></a>
 %s
<noscript>
<font color="red">
JavaScript is turned off in your web browser. Turn it on to make this site functional, then refresh the page.
</font><br><br>
</noscript>
''' % (EXT_URL, EXT_URL, EXT_URL, EXTBASEX_URL, DOJO_URL, customHead, sanitizeHtml(os.environ['REQUEST_URI']), customBodyStart)))

pageTemplateHeadStart = Template(re.sub(r'portal_images', os.path.join(REL_URL, 'portal_images'), '''
<html>
 <head>
  <title>${title}</title>
  <!--EXT_BEGIN-->
  <link rel="stylesheet" type="text/css" href="%s/resources/css/ext-all.css" />
  <script type="text/javascript" src="%s/adapter/ext/ext-base.js"> </script>
  <script type="text/javascript" src="%s/ext-all-debug.js"> </script>
  <script type="text/javascript" src="%s/ext-basex.js"> </script>
  <script type="text/javascript">
      Ext.QuickTips.init();
  </script>
  <!--EXT_END-->
  <!--DOJO_BEGIN-->
  <script type="text/javascript">
    djConfig = { isDebug: false };
  </script>
  <script type="text/javascript" src="%s"></script>
  <script type="text/javascript">
    dojo.require("dojo.event.*");
    dojo.require("dojo.io.*");
    dojo.require("dojo.widget.ComboBox");
  </script>
  <script type="text/javascript">
    function waitForLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadXmlToWindow(str, id);
      }else {
        dojo.lang.setTimeout(waitForLoad, 300, id);
      }
    }

    function getXmlStr(id) {
      var xmlDoc = document.getElementById(id);
      return getXmlStringFromCDATAString(xmlDoc.childNodes[0].nodeValue);
    }

    function loadXmlToWindow(str, id) {
      var newwin = window.open('data:text/xml,' + str, id);
    }

    function loadResultToWindow(str) {
      var newwin = window.open();
      var newdoc = newwin.document;
      newdoc.write(str);
      newdoc.close();
    }

    function waitForResultLoad(id) {
      var str = getXmlStr(id);
      if (str.length != 0) {
        loadResultToWindow(str);
      }else {
        dojo.lang.setTimeout(waitForResultLoad, 300, id);
      }
    }
  </script>
  <!--DOJO_END-->
  %s
  ${additionalHead}
''' % (EXT_URL, EXT_URL, EXT_URL, EXTBASEX_URL, DOJO_URL, customHead)))

pageTemplateHeadEnd = Template(re.sub(r'portal_images', os.path.join(REL_URL, 'portal_images'), '''
  ${additionalHead}
</head>
 <body ${bodyOnload}>
 <a href="%s#main"><img src="portal_images/spacer.gif" alt="Follow this link to skip to the main content"
width="1" height="1" hspace="0" vspace="0" border="0" align="left"></a>
 %s
<noscript>
<font color="red">
JavaScript is turned off in your web browser. Turn it on to make this site functional, then refresh the page.
</font><br><br>
</noscript>
''' % (sanitizeHtml(os.environ['REQUEST_URI']), customBodyStart)))

pageTemplateFoot = Template('%s</body></html>' % customBodyEnd)
